// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function $bang(x) {
  return x[0];
}

var Yojson_conv_error = 0;

var Yojson_conv = 0;

var Yojsonable = 0;

var Yojson = 0;

exports.Yojson_conv_error = Yojson_conv_error;
exports.Yojson_conv = Yojson_conv;
exports.Yojsonable = Yojsonable;
exports.Yojson = Yojson;
exports.$bang = $bang;
/* No side effect */
